
spring.server=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/e_com
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true